---
title: Execute um script após um intervalo de tempo
hero_image: images/banner.png
description: Execute um script após um intervalo de tempo
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Execute um script após um intervalo de tempo
