---
title: Spouštění skriptu po časové prodlevě
hero_image: images/banner.png
description: Spouštění skriptu po časové prodlevě
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Spouštění skriptu po časové prodlevě
