---
title: Ejecuta un script después de un tiempo de retraso
hero_image: images/banner.png
description: Ejecuta un script después de un tiempo de retraso
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Ejecuta un script después de un tiempo de retraso
