---
title: Uruchom skrypt z opóźnieniem
hero_image: images/banner.png
description: Uruchom skrypt z opóźnieniem
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Uruchom skrypt z opóźnieniem
