---
title: Esegui uno script dopo una pausa
hero_image: images/banner.png
description: Esegui uno script dopo una pausa
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Esegui uno script dopo una pausa
